/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by update_website.ps1
 */

let projects = [
    {
        id: 'doors',
        title: 'Doors',
        category: 'doors',
        description: 'Exclusive collection of doors.',
        details: { 'Collection Type': 'Premium Portfolio' },
        sections: [{ title: 'Royal Teak Door', images: ['assets/projects/doors/royal-teak-door/sample.jpg', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035911.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035915.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035918.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035921.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035926.png'] }, { title: 'Other Designs', images: ['assets/projects/doors/Screenshot 2026-01-15 035911.png', 'assets/projects/doors/Screenshot 2026-01-15 035915.png', 'assets/projects/doors/Screenshot 2026-01-15 035918.png', 'assets/projects/doors/Screenshot 2026-01-15 035921.png', 'assets/projects/doors/Screenshot 2026-01-15 035926.png'] }],
        images: ['assets/projects/doors/royal-teak-door/sample.jpg', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035911.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035915.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035918.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035921.png', 'assets/projects/doors/royal-teak-door/Screenshot 2026-01-15 035926.png', 'assets/projects/doors/Screenshot 2026-01-15 035911.png', 'assets/projects/doors/Screenshot 2026-01-15 035915.png', 'assets/projects/doors/Screenshot 2026-01-15 035918.png', 'assets/projects/doors/Screenshot 2026-01-15 035921.png', 'assets/projects/doors/Screenshot 2026-01-15 035926.png']
    },
    {
        id: 'kitchens',
        title: 'Kitchens',
        category: 'kitchens',
        description: 'Exclusive collection of kitchens.',
        details: { 'Collection Type': 'Premium Portfolio' },
        sections: [{ title: 'Modern Kitchen', images: ['assets/projects/kitchens/modern-kitchen/sample.jpg', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 033958.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 034027.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 082925.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 083803.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 090833.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 151440.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 153002.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 153457.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 154128.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 194515.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-12 230904.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-15 032418.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-15 033025.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-15 033809.png'] }],
        images: ['assets/projects/kitchens/modern-kitchen/sample.jpg', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 033958.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 034027.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 082925.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 083803.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 090833.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 151440.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 153002.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 153457.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 154128.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-10 194515.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-12 230904.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-15 032418.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-15 033025.png', 'assets/projects/kitchens/modern-kitchen/Screenshot 2026-01-15 033809.png']
    },
    {
        id: 'mohid',
        title: 'Mohid',
        category: 'mohid',
        description: 'Exclusive collection of mohid.',
        details: { 'Collection Type': 'Premium Portfolio' },
        sections: [{ title: 'Gallery', images: ['assets/projects/mohid/472013757_595354769912512_333410787710450628_n.jpg', 'assets/projects/mohid/Screenshot 2026-01-10 033958.png', 'assets/projects/mohid/Screenshot 2026-01-10 034027.png', 'assets/projects/mohid/Screenshot 2026-01-10 082925.png', 'assets/projects/mohid/Screenshot 2026-01-10 083803.png', 'assets/projects/mohid/Screenshot 2026-01-10 090833.png', 'assets/projects/mohid/Screenshot 2026-01-10 151440.png', 'assets/projects/mohid/Screenshot 2026-01-10 153002.png', 'assets/projects/mohid/Screenshot 2026-01-10 153457.png', 'assets/projects/mohid/Screenshot 2026-01-10 154128.png', 'assets/projects/mohid/Screenshot 2026-01-10 194515.png', 'assets/projects/mohid/Screenshot 2026-01-12 230904.png', 'assets/projects/mohid/Screenshot 2026-01-15 032418.png', 'assets/projects/mohid/Screenshot 2026-01-15 033025.png', 'assets/projects/mohid/Screenshot 2026-01-15 033809.png'] }],
        images: ['assets/projects/mohid/472013757_595354769912512_333410787710450628_n.jpg', 'assets/projects/mohid/Screenshot 2026-01-10 033958.png', 'assets/projects/mohid/Screenshot 2026-01-10 034027.png', 'assets/projects/mohid/Screenshot 2026-01-10 082925.png', 'assets/projects/mohid/Screenshot 2026-01-10 083803.png', 'assets/projects/mohid/Screenshot 2026-01-10 090833.png', 'assets/projects/mohid/Screenshot 2026-01-10 151440.png', 'assets/projects/mohid/Screenshot 2026-01-10 153002.png', 'assets/projects/mohid/Screenshot 2026-01-10 153457.png', 'assets/projects/mohid/Screenshot 2026-01-10 154128.png', 'assets/projects/mohid/Screenshot 2026-01-10 194515.png', 'assets/projects/mohid/Screenshot 2026-01-12 230904.png', 'assets/projects/mohid/Screenshot 2026-01-15 032418.png', 'assets/projects/mohid/Screenshot 2026-01-15 033025.png', 'assets/projects/mohid/Screenshot 2026-01-15 033809.png']
    }
];
