<#
.SYNOPSIS
    Generates js/data.js from the folder structure in assets/projects.
.DESCRIPTION
    This script looks at 'assets/projects'.
    1st Level Folders = Categories (e.g. 'doors', 'kitchens')
    2nd Level Folders = Projects (e.g. 'royal-teak-door')
    Files inside 2nd Level = Images.
    
    It also looks for a 'info.txt' file in each project folder for description/details.
#>

$SiteRoot = "c:/Users/mohid/Documents/Madni Wooden Legacy Website"
$ProjectsRoot = Join-Path $SiteRoot "assets/projects"
$OutputFile = Join-Path $SiteRoot "js/data.js"

if (-not (Test-Path $ProjectsRoot)) {
    Write-Host "Error: Project folder not found at $ProjectsRoot" -ForegroundColor Red
    exit
}

$ProjectsList = @()

# Get Categories (Level 1 Folders)
$Categories = Get-ChildItem -Path $ProjectsRoot -Directory

foreach ($Cat in $Categories) {
    $CategoryName = $Cat.Name.ToLower()
    
    # === GENERIC PORTFOLIO LOGIC (Every Category = 1 Project) ===
    # This logic is now applied universally as requested.
    
    $ProjectId = $CategoryName
    $TextInfo = (Get-Culture).TextInfo
    $ProjectTitle = $TextInfo.ToTitleCase($CategoryName)
    
    # Try to make title fancy if simple name
    if ($ProjectTitle -notmatch "Portfolio|Collection") {
        $ProjectTitle = $ProjectTitle
    }
    
    $SectionsList = @()
    $AllPaths = @()

    # 1. Get Subfolders acting as Sections (e.g. "Modern Kitchen", "Royal Teak Door")
    $SubFolders = Get-ChildItem -Path $Cat.FullName -Directory
    foreach ($Sub in $SubFolders) {
        $SectionTitle = $Sub.Name -replace "-", " "
        $SectionTitle = $TextInfo.ToTitleCase($SectionTitle)
        
        # Robust filter for images
        $SubImages = Get-ChildItem -Path $Sub.FullName -File | Where-Object { $_.Extension -match '\.(jpg|jpeg|png|webp)$' }
        
        if ($SubImages.Count -gt 0) {
           $ImagePaths = @()
           foreach ($Img in $SubImages) {
               $FullPath = $Img.FullName -replace "\\", "/"
               $RootStandard = $SiteRoot -replace "\\", "/"
               $RootPattern = [Regex]::Escape($RootStandard)
               $RelPath = $FullPath -replace "^$RootPattern", ""
               if ($RelPath.StartsWith("/")) { $RelPath = $RelPath.Substring(1) }
               $ImagePaths += "'$RelPath'"
               $AllPaths += "'$RelPath'"
           }
           $ImgsStr = $ImagePaths -join ","
           $SectionsList += "{ title: '$SectionTitle', images: [$ImgsStr] }"
        }
    }
    
    # 2. Add loose images in the root of the category as "Gallery" or "Designs"
    $LooseImages = Get-ChildItem -Path $Cat.FullName -File | Where-Object { $_.Extension -match '\.(jpg|jpeg|png|webp)$' }
    if ($LooseImages.Count -gt 0) {
        $ImagePaths = @()
        foreach ($Img in $LooseImages) {
           $FullPath = $Img.FullName -replace "\\", "/"
           $RootStandard = $SiteRoot -replace "\\", "/"
           $RootPattern = [Regex]::Escape($RootStandard)
           $RelPath = $FullPath -replace "^$RootPattern", ""
           if ($RelPath.StartsWith("/")) { $RelPath = $RelPath.Substring(1) }
           $ImagePaths += "'$RelPath'"
           $AllPaths += "'$RelPath'"
        }
        $ImgsStr = $ImagePaths -join ","
        # If we have named sections, call this "Other Designs", otherwise just "Gallery"
        if ($SectionsList.Count -gt 0) {
             $SectionsList += "{ title: 'Other Designs', images: [$ImgsStr] }"
        } else {
             $SectionsList += "{ title: 'Gallery', images: [$ImgsStr] }"
        }
    }

    # Only create the project if we found images
    if ($AllPaths.Count -gt 0) {
        $SectionsJson = $SectionsList -join ","
        $AllImagesStr = $AllPaths -join ","

        # Use the first image as the representative thumbnail if available
        $ThumbLine = ""
        # The logic below allows the specific 'images' array to be populated which main.js uses for the card thumbnail
        
        $ProjectJson = "
    {
        id: '$ProjectId',
        title: '$ProjectTitle',
        category: '$CategoryName',
        description: 'Exclusive collection of $CategoryName.',
        details: { 'Collection Type': 'Premium Portfolio' },
        sections: [$SectionsJson],
        images: [$AllImagesStr]
    }"
        $ProjectsList += $ProjectJson
    }
}

# Write to file
$FinalContent = "/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by update_website.ps1
 */

const projects = [" + ($ProjectsList -join ",") + "
];"

Set-Content -Path $OutputFile -Value $FinalContent -Encoding utf8
Write-Host "Success! Website updated with $($ProjectsList.Count) projects." -ForegroundColor Green
Write-Host "Opened $OutputFile"
